version: '3.6'

services:
  mkdocs-dev:
    image: python:3
    ports:
      - 127.0.0.1:8000:8000
    volumes:
      - ./:/home/wiki/docs
    working_dir: /home/wiki/docs
    entrypoint: ['bash', '-c', 'pip install -i https://mirrors.aliyun.com/pypi/simple/ mkdocs-material && mkdocs serve --dev-addr 0.0.0.0:8000 --verbose']
